### ISSUE TITLE
Add option to use released images in setup script

### ISSUE THREAD

**Issue by dsimansk** [syndesisio/syndesis-system-tests#16]
@iocanel I'd like to add simple switch to avoid ImageStream override in setup.sh script. I was thinking about `SYNDESIS_DOCKERHUB_IMAGES` or `SYNDESIS_RELEASED_IMAGES`. Wdyt? Of course I will send PR if we settle on a name :)

**Comment by iocanel** [comment]
Sounds good to me! Feel free to pickup any name you like! They are both good.

**Comment by dsimansk** [comment]
Done via #21.
